[package]
name = "age_viewer"
version = "0.1.0"
edition = "2024"
description = "Gundam AGE PSP model/texture preview and glTF extraction tool"
default-run = "age_viewer"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
flate2 = "1"
eframe = { version = "0.33.3", default-features = false, features = [
    "wgpu",
    "default_fonts",
] }
egui = "0.33.3"
wgpu = { version = "27", default-features = false, features = [
    "wgsl",
    "dx12",
    "vulkan",
] }
bytemuck = { version = "1", features = ["derive"] }
rfd = "0.17.2"
image = { version = "0.25.10", default-features = false, features = ["png"] }
ttf-parser = "0.25"
dirs = "6"

[profile.release]
opt-level = "s"
codegen-units = 256
strip = true
