#!/usr/bin/env python3
"""Experimental Gundam AGE PSP XMPR/XPVB mesh decoder.

This tool uses the XPVB layout implemented by Tiniifan's StudioElevenLib, then
adds a PSP-specific fallback for AGE files where XPVI is a 12-byte primitive
header without an embedded compressed index buffer.

Confirmed:
- XMPR/XPRM headers and XPVB offsets/lengths.
- XPVB attribute table is Level-5 compressed.
- XPVB vertex buffer is Level-5 compressed.
- In sampled float32 XPVB files, slot 0 is position float32x3 and slot 4 is UV0 float32x2.
- In sampled 16-bit XPVB files, slot 0 decodes as signed normalized x3 and
  slot 4 decodes as unsigned normalized x2. When slot 7 contains implicit
  node weights, slot 0 is usable bind-pose position geometry.

Experimental:
- AGE PSP XPVI has primitive type 2 (triangle strip) but no index payload in
  sampled files. OBJ faces generated by this tool therefore use vertex order as
  a triangle strip and must be treated as a working hypothesis.
"""

from __future__ import annotations

import argparse
import json
import math
import struct
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from age_xpck_tool import XpckError, decompress_level5  # noqa: E402


@dataclass
class Attribute:
    slot: int
    count: int
    offset: int
    size: int
    type: int


@dataclass
class Vertex:
    position: tuple[float, float, float]
    uv0: tuple[float, float] | None
    packed_slot1_rgba: tuple[int, int, int, int] | None
    position_raw_s16: tuple[int, int, int] | None
    implicit_node_weights_u8: tuple[int, ...] | None


@dataclass
class XpvbInfo:
    offset: int
    length: int
    att_buffer_offset: int
    unknown_offset: int
    vertex_buffer_offset: int
    stride: int
    vertex_count: int
    att_compression: str
    att_decoded_size: int
    vertex_compression: str
    vertex_decoded_size: int
    unknown_bytes_hex: str
    attributes: list[Attribute]
    position_format: str
    uv0_format: str
    warnings: list[str]


@dataclass
class XpviInfo:
    offset: int
    length: int
    primitive_type: int
    faces_offset: int
    face_count: int
    has_embedded_index_payload: bool


@dataclass
class GeometryStats:
    bounds_min: tuple[float, float, float] | None
    bounds_max: tuple[float, float, float] | None
    unique_position_count: int
    unique_position_ratio: float
    inferred_face_count: int
    exported_face_count: int
    nondegenerate_face_count: int
    degenerate_face_count: int
    degenerate_face_ratio: float
    max_triangle_area: float
    position_semantic: str


@dataclass
class MeshInfo:
    source: str
    mesh_name: str
    material_name: str
    draw_priority: int
    mesh_type: int
    nodes_count: int
    node_hashes: list[str]
    xpvb: XpvbInfo
    xpvi: XpviInfo
    vertex_count: int
    face_count: int
    triangulation: str
    geometry: GeometryStats
    warnings: list[str]


MeshExport = tuple[MeshInfo, list[Vertex], list[tuple[int, int, int]]]


def u16(data: bytes, offset: int) -> int:
    return struct.unpack_from("<H", data, offset)[0]


def u32(data: bytes, offset: int) -> int:
    return struct.unpack_from("<I", data, offset)[0]


def read_c_string(data: bytes, offset: int, length: int) -> str:
    if offset <= 0 or offset >= len(data) or length <= 0:
        return ""
    raw = data[offset : min(len(data), offset + length)]
    raw = raw.split(b"\x00", 1)[0]
    return raw.decode("shift-jis", errors="replace")


def parse_attributes(att: bytes) -> list[Attribute]:
    attributes: list[Attribute] = []
    for slot in range(10):
        base = slot * 4
        if base + 4 > len(att):
            break
        count, offset, size, typ = att[base : base + 4]
        attributes.append(Attribute(slot=slot, count=count, offset=offset, size=size, type=typ))
    return attributes


def attr_by_slot(attributes: list[Attribute], slot: int) -> Attribute | None:
    for attr in attributes:
        if attr.slot == slot:
            return attr
    return None


def attr_is_active(attr: Attribute | None) -> bool:
    return attr is not None and attr.count > 0 and attr.size > 0


def read_float_tuple(blob: bytes, offset: int, count: int) -> tuple[float, ...]:
    return struct.unpack_from("<" + "f" * count, blob, offset)


def read_s16_norm_tuple(blob: bytes, offset: int, count: int) -> tuple[float, ...]:
    values = struct.unpack_from("<" + "h" * count, blob, offset)
    return tuple(value / 32768.0 for value in values)


def read_s16_tuple(blob: bytes, offset: int, count: int) -> tuple[int, ...]:
    return struct.unpack_from("<" + "h" * count, blob, offset)


def read_u16_norm_tuple(blob: bytes, offset: int, count: int) -> tuple[float, ...]:
    values = struct.unpack_from("<" + "H" * count, blob, offset)
    return tuple(value / 32768.0 for value in values)


def decode_xpvb(data: bytes, xprm_offset: int) -> tuple[XpvbInfo, list[Vertex]]:
    xpvb_rel = u32(data, xprm_offset + 0x04)
    xpvb_len = u32(data, xprm_offset + 0x08)
    xpvb_offset = xprm_offset + xpvb_rel
    xpvb = data[xpvb_offset : xpvb_offset + xpvb_len]
    if len(xpvb) < 0x10 or xpvb[:4] != b"XPVB":
        raise XpckError(f"XPVB block missing at 0x{xpvb_offset:X}")

    att_off, unk_off, vtx_off, stride, vertex_count = struct.unpack_from("<HHHHI", xpvb, 0x04)
    att_method, att = decompress_level5(xpvb[att_off:unk_off])
    vtx_method, vtx = decompress_level5(xpvb[vtx_off:])
    attributes = parse_attributes(att)

    warnings: list[str] = []
    pos_attr = attr_by_slot(attributes, 0)
    uv_attr = attr_by_slot(attributes, 4)
    slot1_attr = attr_by_slot(attributes, 1)
    if not pos_attr:
        raise XpckError("XPVB has no position attribute in slot 0")

    position_format = "unsupported"
    if pos_attr.size == 12 and pos_attr.type == 2 and pos_attr.offset + 12 <= stride:
        position_format = "float32x3"
    elif pos_attr.size == 16 and pos_attr.type == 2 and pos_attr.offset + 16 <= stride:
        position_format = "float32x4_xyz"
    elif pos_attr.size == 6 and pos_attr.type == 2 and pos_attr.offset + 6 <= stride:
        position_format = "s16_normx3"

    uv0_format = "absent"
    if attr_is_active(uv_attr):
        if uv_attr.size == 8 and uv_attr.type == 2 and uv_attr.offset + 8 <= stride:
            uv0_format = "float32x2"
        elif uv_attr.size == 4 and uv_attr.type == 2 and uv_attr.offset + 4 <= stride:
            uv0_format = "u16_normx2"
        else:
            uv0_format = "unsupported"

    if position_format == "unsupported":
        warnings.append(
            "Position attribute slot 0 is not a supported format "
            f"(count={pos_attr.count}, offset={pos_attr.offset}, size={pos_attr.size}, type={pos_attr.type}); "
            "vertex positions were not exported."
        )
    if uv0_format == "unsupported" and attr_is_active(uv_attr):
        warnings.append(
            "UV attribute slot 4 is not a supported format "
            f"(count={uv_attr.count}, offset={uv_attr.offset}, size={uv_attr.size}, type={uv_attr.type}); "
            "UVs were not exported."
        )
    if len(vtx) != stride * vertex_count:
        warnings.append(
            f"Decoded vertex buffer size {len(vtx)} does not match stride*vertex_count "
            f"({stride}*{vertex_count}={stride * vertex_count})."
        )

    vertices: list[Vertex] = []
    if position_format == "unsupported":
        info = XpvbInfo(
            offset=xpvb_offset,
            length=xpvb_len,
            att_buffer_offset=att_off,
            unknown_offset=unk_off,
            vertex_buffer_offset=vtx_off,
            stride=stride,
            vertex_count=vertex_count,
            att_compression=att_method,
            att_decoded_size=len(att),
            vertex_compression=vtx_method,
            vertex_decoded_size=len(vtx),
            unknown_bytes_hex=xpvb[unk_off:vtx_off].hex(" ").upper(),
            attributes=attributes,
            position_format=position_format,
            uv0_format=uv0_format,
            warnings=warnings,
        )
        return info, vertices

    for index in range(vertex_count):
        row = index * stride
        if row + stride > len(vtx):
            warnings.append(f"Stopped at vertex {index}; row exceeds decoded vertex buffer.")
            break

        if position_format == "float32x3":
            position = read_float_tuple(vtx, row + pos_attr.offset, 3)
            position_raw_s16 = None
        elif position_format == "float32x4_xyz":
            position = read_float_tuple(vtx, row + pos_attr.offset, 4)[:3]
            position_raw_s16 = None
        elif position_format == "s16_normx3":
            position_raw_s16 = read_s16_tuple(vtx, row + pos_attr.offset, 3)
            position = tuple(value / 32768.0 for value in position_raw_s16)
        else:
            raise XpckError(f"unsupported position format: {position_format}")

        uv0 = None
        if attr_is_active(uv_attr) and uv0_format == "float32x2":
            uv = read_float_tuple(vtx, row + uv_attr.offset, 2)
            uv0 = (uv[0], 1.0 - uv[1])
        elif attr_is_active(uv_attr) and uv0_format == "u16_normx2":
            uv = read_u16_norm_tuple(vtx, row + uv_attr.offset, 2)
            uv0 = (uv[0], 1.0 - uv[1])

        packed_rgba = None
        if slot1_attr and slot1_attr.size == 4:
            raw = vtx[row + slot1_attr.offset : row + slot1_attr.offset + 4]
            if len(raw) == 4:
                packed_rgba = tuple(raw)  # observed as grayscale/RGBA-like bytes in AGE PSP

        implicit_node_weights = None
        slot7_attr = attr_by_slot(attributes, 7)
        if attr_is_active(slot7_attr) and slot7_attr.size == 8:
            raw = vtx[row + slot7_attr.offset : row + slot7_attr.offset + 8]
            if len(raw) == 8:
                implicit_node_weights = tuple(raw)

        vertices.append(
            Vertex(
                position=(position[0], position[1], position[2]),
                uv0=uv0,
                packed_slot1_rgba=packed_rgba,  # type: ignore[arg-type]
                position_raw_s16=position_raw_s16,  # type: ignore[arg-type]
                implicit_node_weights_u8=implicit_node_weights,
            )
        )

    info = XpvbInfo(
        offset=xpvb_offset,
        length=xpvb_len,
        att_buffer_offset=att_off,
        unknown_offset=unk_off,
        vertex_buffer_offset=vtx_off,
        stride=stride,
        vertex_count=vertex_count,
        att_compression=att_method,
        att_decoded_size=len(att),
        vertex_compression=vtx_method,
        vertex_decoded_size=len(vtx),
        unknown_bytes_hex=xpvb[unk_off:vtx_off].hex(" ").upper(),
        attributes=attributes,
        position_format=position_format,
        uv0_format=uv0_format,
        warnings=warnings,
    )
    return info, vertices


def decode_xpvi(data: bytes, xprm_offset: int) -> XpviInfo:
    xpvi_rel = u32(data, xprm_offset + 0x0C)
    xpvi_len = u32(data, xprm_offset + 0x10)
    xpvi_offset = xprm_offset + xpvi_rel
    xpvi = data[xpvi_offset : xpvi_offset + xpvi_len]
    if len(xpvi) < 0x0C or xpvi[:4] != b"XPVI":
        raise XpckError(f"XPVI block missing at 0x{xpvi_offset:X}")

    primitive_type, faces_offset, face_count = struct.unpack_from("<HHI", xpvi, 0x04)
    return XpviInfo(
        offset=xpvi_offset,
        length=xpvi_len,
        primitive_type=primitive_type,
        faces_offset=faces_offset,
        face_count=face_count,
        has_embedded_index_payload=xpvi_len > 0x0C and faces_offset >= 0x0C,
    )


def triangle_strip_faces(vertex_count: int) -> list[tuple[int, int, int]]:
    faces: list[tuple[int, int, int]] = []
    flip = False
    for i in range(vertex_count - 2):
        if flip:
            faces.append((i + 2, i + 1, i + 3))
        else:
            faces.append((i + 1, i + 2, i + 3))
        flip = not flip
    return faces


def sequential_triangle_faces(vertex_count: int) -> list[tuple[int, int, int]]:
    faces = []
    for i in range(0, vertex_count - 2, 3):
        faces.append((i + 1, i + 2, i + 3))
    return faces


def triangle_area(a: tuple[float, float, float], b: tuple[float, float, float], c: tuple[float, float, float]) -> float:
    ux, uy, uz = b[0] - a[0], b[1] - a[1], b[2] - a[2]
    vx, vy, vz = c[0] - a[0], c[1] - a[1], c[2] - a[2]
    cross = (uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx)
    return math.sqrt(cross[0] * cross[0] + cross[1] * cross[1] + cross[2] * cross[2]) * 0.5


def nondegenerate_faces(vertices: list[Vertex], faces: list[tuple[int, int, int]]) -> list[tuple[int, int, int]]:
    if not vertices or not faces:
        return []
    positions = [vertex.position for vertex in vertices]
    return [
        face
        for face in faces
        if triangle_area(positions[face[0] - 1], positions[face[1] - 1], positions[face[2] - 1]) > 1e-8
    ]


def geometry_stats(
    vertices: list[Vertex],
    inferred_faces: list[tuple[int, int, int]],
    exported_faces: list[tuple[int, int, int]],
    position_format: str,
    skinned_bind_pose: bool = False,
) -> tuple[GeometryStats, list[str]]:
    warnings: list[str] = []
    if not vertices:
        return (
            GeometryStats(
                bounds_min=None,
                bounds_max=None,
                unique_position_count=0,
                unique_position_ratio=0.0,
                inferred_face_count=len(inferred_faces),
                exported_face_count=len(exported_faces),
                nondegenerate_face_count=0,
                degenerate_face_count=0,
                degenerate_face_ratio=0.0,
                max_triangle_area=0.0,
                position_semantic="absent",
            ),
            warnings,
        )

    positions = [vertex.position for vertex in vertices]
    bounds_min = tuple(min(position[i] for position in positions) for i in range(3))
    bounds_max = tuple(max(position[i] for position in positions) for i in range(3))
    unique_position_count = len({tuple(round(component, 6) for component in position) for position in positions})
    unique_position_ratio = unique_position_count / len(vertices)

    areas = [triangle_area(positions[a - 1], positions[b - 1], positions[c - 1]) for a, b, c in inferred_faces]
    nondegenerate_face_count = sum(1 for area in areas if area > 1e-8)
    degenerate_face_count = len(areas) - nondegenerate_face_count
    degenerate_face_ratio = (degenerate_face_count / len(areas)) if areas else 0.0
    max_triangle_area = max(areas) if areas else 0.0

    position_semantic = "skinned_bind_pose_position" if skinned_bind_pose else "likely_position"
    if skinned_bind_pose:
        warnings.append(
            "Normalized signed 16-bit positions are exported in their usable bind pose; "
            "implicit 8-byte node weights and MBN data are retained for optional animation."
        )
    elif position_format == "s16_normx3" and unique_position_ratio < 0.05:
        position_semantic = "unconfirmed_direction_like"
        warnings.append(
            f"Decoded s16_normx3 slot has only {unique_position_count} unique vectors for {len(vertices)} vertices; "
            "this looks direction/normal-like and is not confirmed position geometry."
        )

    return (
        GeometryStats(
            bounds_min=bounds_min,  # type: ignore[arg-type]
            bounds_max=bounds_max,  # type: ignore[arg-type]
            unique_position_count=unique_position_count,
            unique_position_ratio=unique_position_ratio,
            inferred_face_count=len(inferred_faces),
            exported_face_count=len(exported_faces),
            nondegenerate_face_count=nondegenerate_face_count,
            degenerate_face_count=degenerate_face_count,
            degenerate_face_ratio=degenerate_face_ratio,
            max_triangle_area=max_triangle_area,
            position_semantic=position_semantic,
        ),
        warnings,
    )


def decode_mesh(
    path: Path, triangulation: str, skip_degenerate_faces: bool = True
) -> tuple[MeshInfo, list[Vertex], list[tuple[int, int, int]]]:
    data = path.read_bytes()
    if len(data) < 0x54 or data[:4] != b"XMPR":
        raise XpckError(f"not an XMPR .prm file: {path}")

    xprm_offset = u32(data, 0x04)
    if xprm_offset <= 0 or xprm_offset + 0x14 > len(data) or data[xprm_offset : xprm_offset + 4] != b"XPRM":
        raise XpckError(f"XPRM header not found at declared offset 0x{xprm_offset:X}")

    xpvb_info, vertices = decode_xpvb(data, xprm_offset)
    xpvi_info = decode_xpvi(data, xprm_offset)

    properties_offset = u32(data, 0x0C)
    draw_priority = 0
    mesh_type = 0
    nodes_count = 0
    node_hashes: list[str] = []
    if properties_offset and properties_offset + 0x3C <= len(data):
        draw_priority = u32(data, properties_offset + 0x30)
        mesh_type = u16(data, properties_offset + 0x34)
        nodes_count = u32(data, properties_offset + 0x38)

    nodes_offset = u32(data, 0x28)
    nodes_length = u32(data, 0x2C)
    if nodes_offset and nodes_length and nodes_offset + nodes_length <= len(data) and nodes_length % 4 == 0:
        node_values = struct.unpack_from("<" + "I" * (nodes_length // 4), data, nodes_offset)
        node_hashes = [f"{value:08X}" for value in node_values]
        nodes_count = len(node_hashes)

    mesh_name = read_c_string(data, u32(data, 0x30), u32(data, 0x34))
    material_name = read_c_string(data, u32(data, 0x38), u32(data, 0x3C))

    warnings = list(xpvb_info.warnings)
    if xpvi_info.primitive_type == 2 and not xpvi_info.has_embedded_index_payload:
        warnings.append("AGE PSP XPVI has no embedded index payload; faces are inferred from vertex order as a triangle strip.")
    if xpvi_info.face_count == 0:
        warnings.append("XPVI face_count is zero in sampled PSP file.")

    if triangulation == "strip":
        inferred_faces = triangle_strip_faces(len(vertices))
    elif triangulation == "list":
        inferred_faces = sequential_triangle_faces(len(vertices))
    elif triangulation == "points":
        inferred_faces = []
    else:
        raise XpckError(f"unknown triangulation mode: {triangulation}")

    if skip_degenerate_faces:
        faces = nondegenerate_faces(vertices, inferred_faces)
    else:
        faces = inferred_faces

    has_implicit_node_weights = bool(node_hashes) and any(
        vertex.implicit_node_weights_u8 is not None for vertex in vertices
    )
    geometry, geometry_warnings = geometry_stats(
        vertices,
        inferred_faces,
        faces,
        xpvb_info.position_format,
        skinned_bind_pose=xpvb_info.position_format == "s16_normx3" and has_implicit_node_weights,
    )
    warnings.extend(geometry_warnings)
    skipped_faces = len(inferred_faces) - len(faces)
    if skipped_faces:
        warnings.append(f"Skipped {skipped_faces} degenerate inferred faces in OBJ export.")

    info = MeshInfo(
        source=str(path),
        mesh_name=mesh_name,
        material_name=material_name,
        draw_priority=draw_priority,
        mesh_type=mesh_type,
        nodes_count=nodes_count,
        node_hashes=node_hashes,
        xpvb=xpvb_info,
        xpvi=xpvi_info,
        vertex_count=len(vertices),
        face_count=len(faces),
        triangulation=triangulation,
        geometry=geometry,
        warnings=warnings,
    )
    return info, vertices, faces


def obj_identifier(value: str, fallback: str) -> str:
    cleaned = "".join(ch if 0x21 <= ord(ch) <= 0x7E and ch not in "\\/" else "_" for ch in value.strip())
    return cleaned or fallback


def write_obj(
    path: Path,
    meshes: list[MeshExport],
    mtllib: str | None = None,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = [
        "# Experimental OBJ generated from Gundam AGE PSP XMPR/XPVB data",
        "# Positions and UVs are decoded from XPVB. Faces may be inferred for PSP AGE.",
    ]
    if mtllib:
        lines.append(f"mtllib {Path(mtllib).name}")

    vertex_base = 0
    vt_base = 0
    for info, vertices, faces in meshes:
        object_name = obj_identifier(info.mesh_name, Path(info.source).stem)
        material_name = obj_identifier(info.material_name, "default_material")
        lines.append(f"o {object_name}")
        lines.append(f"# source {info.source}")
        lines.append(f"# material {info.material_name}")
        lines.append(f"usemtl {material_name}")
        for warning in info.warnings:
            lines.append(f"# warning {warning}")

        has_uv = any(v.uv0 is not None for v in vertices)
        for vertex in vertices:
            x, y, z = vertex.position
            lines.append(f"v {x:.8g} {y:.8g} {z:.8g}")
        if has_uv:
            for vertex in vertices:
                if vertex.uv0 is None:
                    lines.append("vt 0 0")
                else:
                    u, v = vertex.uv0
                    lines.append(f"vt {u:.8g} {v:.8g}")

        for a, b, c in faces:
            if has_uv:
                lines.append(
                    f"f {a + vertex_base}/{a + vt_base} "
                    f"{b + vertex_base}/{b + vt_base} "
                    f"{c + vertex_base}/{c + vt_base}"
                )
            else:
                lines.append(f"f {a + vertex_base} {b + vertex_base} {c + vertex_base}")

        vertex_base += len(vertices)
        if has_uv:
            vt_base += len(vertices)

    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def vertex_weight_records(vertex: Vertex, node_hashes: list[str]) -> list[dict]:
    if vertex.implicit_node_weights_u8 is None:
        return []

    scaled_records = []
    for slot, raw_weight in enumerate(vertex.implicit_node_weights_u8):
        if raw_weight == 0:
            continue
        scaled = min(raw_weight, 128) / 128.0
        scaled_records.append(
            {
                "slot": slot,
                "node_hash": node_hashes[slot] if slot < len(node_hashes) else None,
                "raw_u8": raw_weight,
                "weight_raw128": scaled,
            }
        )

    total = sum(record["weight_raw128"] for record in scaled_records)
    if total > 0:
        for record in scaled_records:
            record["weight_normalized"] = record["weight_raw128"] / total
    return scaled_records


def build_weight_manifest(meshes: list[MeshExport], obj_path: Path | None = None) -> dict:
    manifest = {
        "format": "age_xmpr_weights_v1",
        "obj": str(obj_path) if obj_path else None,
        "weight_source_attribute_slot": 7,
        "node_table_source": "XMPR node_hashes",
        "normalization": {
            "raw_full_weight": 128,
            "weight_raw128": "min(raw_u8, 128) / 128.0",
            "weight_normalized": "weight_raw128 divided by the per-vertex sum of nonzero weights",
        },
        "mesh_count": len(meshes),
        "vertex_count": 0,
        "vertices_with_raw_weight_count": 0,
        "weighted_mesh_count": 0,
        "weighted_vertex_count": 0,
        "weight_record_count": 0,
        "unmapped_weight_record_count": 0,
        "meshes": [],
    }

    obj_vertex_base = 1
    for info, vertices, _faces in meshes:
        weighted_vertices = []
        raw_weight_vertices = 0
        mesh_weight_records = 0
        mesh_unmapped_records = 0

        for vertex_index, vertex in enumerate(vertices):
            if vertex.implicit_node_weights_u8 is not None:
                raw_weight_vertices += 1
            records = vertex_weight_records(vertex, info.node_hashes)
            if not records:
                continue
            mesh_weight_records += len(records)
            mesh_unmapped_records += sum(1 for record in records if record["node_hash"] is None)
            weighted_vertices.append(
                {
                    "index": vertex_index,
                    "obj_vertex_index": obj_vertex_base + vertex_index,
                    "position": list(vertex.position),
                    "position_raw_s16": list(vertex.position_raw_s16) if vertex.position_raw_s16 else None,
                    "uv0": list(vertex.uv0) if vertex.uv0 else None,
                    "weights": records,
                }
            )

        mesh_record = {
            "source": info.source,
            "mesh_name": info.mesh_name,
            "material_name": info.material_name,
            "node_hashes": info.node_hashes,
            "obj_vertex_start": obj_vertex_base,
            "vertex_count": len(vertices),
            "vertices_with_raw_weight_count": raw_weight_vertices,
            "weighted_vertex_count": len(weighted_vertices),
            "unweighted_vertex_count": len(vertices) - len(weighted_vertices),
            "weight_record_count": mesh_weight_records,
            "unmapped_weight_record_count": mesh_unmapped_records,
            "vertices": weighted_vertices,
        }
        manifest["meshes"].append(mesh_record)
        manifest["vertex_count"] += len(vertices)
        manifest["vertices_with_raw_weight_count"] += raw_weight_vertices
        if weighted_vertices:
            manifest["weighted_mesh_count"] += 1
        manifest["weighted_vertex_count"] += len(weighted_vertices)
        manifest["weight_record_count"] += mesh_weight_records
        manifest["unmapped_weight_record_count"] += mesh_unmapped_records
        obj_vertex_base += len(vertices)

    return manifest


def weight_manifest_summary(manifest: dict, path: Path | None = None) -> dict:
    summary = {
        "format": manifest["format"],
        "mesh_count": manifest["mesh_count"],
        "vertex_count": manifest["vertex_count"],
        "vertices_with_raw_weight_count": manifest["vertices_with_raw_weight_count"],
        "weighted_mesh_count": manifest["weighted_mesh_count"],
        "weighted_vertex_count": manifest["weighted_vertex_count"],
        "weight_record_count": manifest["weight_record_count"],
        "unmapped_weight_record_count": manifest["unmapped_weight_record_count"],
    }
    if path is not None:
        summary["manifest"] = str(path)
    return summary


def write_weight_manifest(path: Path, meshes: list[MeshExport], obj_path: Path | None = None) -> dict:
    path.parent.mkdir(parents=True, exist_ok=True)
    manifest = build_weight_manifest(meshes, obj_path)
    path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    return manifest


def iter_prm_inputs(inputs: list[str]) -> list[Path]:
    paths: list[Path] = []
    for item in inputs:
        path = Path(item)
        if path.is_dir():
            paths.extend(sorted(path.rglob("*.prm")))
        else:
            paths.append(path)
    return paths


def command_export_obj(args: argparse.Namespace) -> int:
    paths = iter_prm_inputs(args.inputs)
    meshes = [decode_mesh(path, args.triangulation, not args.keep_degenerate_faces) for path in paths]
    obj_path = Path(args.out)
    write_obj(obj_path, meshes, args.mtllib)

    weights_path = Path(args.weights_json) if args.weights_json else obj_path.with_suffix(".weights.json")
    weights_manifest = write_weight_manifest(weights_path, meshes, obj_path)

    manifest = {
        "obj": str(obj_path),
        "mtllib": args.mtllib,
        "weights": weight_manifest_summary(weights_manifest, weights_path),
        "mesh_count": len(meshes),
        "meshes": [asdict(mesh[0]) for mesh in meshes],
    }
    manifest_path = Path(args.json) if args.json else obj_path.with_suffix(".obj.json")
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Wrote OBJ: {args.out}")
    print(f"Weights: {weights_path}")
    print(f"Meshes: {len(meshes)}")
    print(f"Manifest: {manifest_path}")
    return 0


def command_info(args: argparse.Namespace) -> int:
    results = []
    for path in iter_prm_inputs(args.inputs):
        info, _, _ = decode_mesh(path, args.triangulation, not args.keep_degenerate_faces)
        results.append(asdict(info))
    print(json.dumps({"mesh_count": len(results), "meshes": results}, indent=2, ensure_ascii=False))
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Experimental Gundam AGE PSP XMPR/XPVB mesh decoder.")
    subparsers = parser.add_subparsers(dest="command", required=True)

    info = subparsers.add_parser("info", help="print decoded XMPR/XPVB metadata")
    info.add_argument("inputs", nargs="+", help=".prm files or directories")
    info.add_argument("--triangulation", choices=["strip", "list", "points"], default="strip")
    info.add_argument("--keep-degenerate-faces", action="store_true")
    info.set_defaults(func=command_info)

    export = subparsers.add_parser("export-obj", help="export decoded vertices to OBJ")
    export.add_argument("inputs", nargs="+", help=".prm files or directories")
    export.add_argument("--out", required=True, help="OBJ output path")
    export.add_argument("--json", help="manifest output path")
    export.add_argument("--weights-json", help="per-vertex weight sidecar output path")
    export.add_argument("--triangulation", choices=["strip", "list", "points"], default="strip")
    export.add_argument("--keep-degenerate-faces", action="store_true")
    export.add_argument("--mtllib", help="optional MTL filename to reference from the OBJ")
    export.set_defaults(func=command_export_obj)

    return parser


def main(argv: list[str] | None = None) -> int:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except XpckError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())





